language: cpp

sudo: required
dist: trusty

compiler:
   - gcc
   - clang

addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         #- llvm-toolchain-trusty-3.7 # travis-ci/apt-source-whitelist#199

      packages:
         - g++-5
         - gcc-5
         #- clang-3.7
         - libboost-filesystem1.55-dev
         - libx11-dev
         - libxrandr-dev

before_install:
   - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee -a /etc/apt/sources.list
   - wget -O - "http://llvm.org/apt/llvm-snapshot.gpg.key"|sudo apt-key add -
   - sudo apt-get update -qq
   - sudo apt-get install clang-3.7 -qq
   - wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz -O cmake.tar.gz
   - tar -xf cmake.tar.gz
   - CMAKE_EXEC="$(pwd)/cmake-3.4.0-Linux-x86_64/bin/cmake"

install:
   - if [[ "$CXX" == "clang++" ]]; then export CXX=clang++-3.7; export CC=clang-3.7; fi
   - if [[ "$CXX" == "g++"     ]]; then export CXX=g++-5;       export CC=gcc-5;     fi
   - cd dependencies/GLEW
   - make extensions
   - cd ../../

script:
   - mkdir build
   - cd build
   - $CMAKE_EXEC ..
   - make -j2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a1f79a324c696ec10d8a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
