language: cpp

compiler:
   - gcc
   - clang

before_install:
   - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
   - sudo apt-get update -qq
   - sudo apt-get install cmake libboost-system-dev libboost-filesystem-dev

script:
   - ./generate.sh qlt
   - mkdir build
   - cd build
   - git --version
   - cmake ..
   - make
