language: cpp

# sudo: false # Use new travis container build -- ppa:kalakris/cmake not whitelisted yet
compiler:
   - gcc
   - clang

addons:
   apt:
      sources:
         - boost-latest
         - ubuntu-toolchain-r-test
         - llvm-toolchain-precise-3.6

      packages:
         - g++-5
         - gcc-5
         - clang-3.6
         - clang-format-3.6
         - libboost-filesystem1.55-dev

install:
   - sudo add-apt-repository ppa:kalakris/cmake -y
   - sudo apt-get update -qq
   - sudo apt-get install -qq cmake
   - if [[ "$CXX" == "clang++" ]]; then export CXX=clang++-3.6; export CC=clang-3.6; fi
   - if [[ "$CXX" == "g++"     ]]; then export CXX=g++-5;       export CC=gcc-5;     fi

script:
   - ./generate.sh qQltp
   - mkdir build
   - cd build
   - cmake ..
   - make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a1f79a324c696ec10d8a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
