language: cpp

compiler:
   - gcc
   - clang

before_install:
   - sudo apt-get install libboost-system-dev libboost-filesystem-dev

script:
   - ./generate.sh qlt
   - mkdir build
   - cd build
   - cmake ..
   - make
