language: cpp

compiler:
   - gcc
   - clang

before_install:
   # We need a c++14 compiler
   - sudo add-apt-repository -y ppa:boost-latest/ppa
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo apt-add-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
   - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
   - sudo apt-get -qq update

install:
   # install boost..
   - sudo apt-get -qq install libboost-system1.55-dev libboost-filesystem1.55-dev

   # install g++ and clang++
   - sudo apt-get -qq install g++-4.9
   - sudo apt-get -qq install clang++-3.5

   - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
   - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.5 50
   - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 50

script:
   - clang --version
   - clang++ --version
   - clang-3.5 --version
   - clang++-3.5 --version
   - $CC --version
   - $CXX --version
   - ./generate.sh qQltp
   - mkdir build
   - cd build
   - cmake ..
   - make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a1f79a324c696ec10d8a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
