language: cpp

compiler:
   - gcc

before_install:
   # We need a c++14 compiler
   - sudo add-apt-repository -y ppa:boost-latest/ppa
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo apt-get -qq update

install:
   # install boost..
   - sudo apt-get -qq install libboost-system1.55-dev libboost-filesystem1.55-dev

   # install g++
   - sudo apt-get -qq install libstdc++-4.9-dev
   - sudo apt-get -qq install g++-4.9
   - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50

script:
   - ./generate.sh qQltp
   - mkdir build
   - cd build
   - cmake ..
   - make
   
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a1f79a324c696ec10d8a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
