language: cpp

sudo: required
dist: trusty

compiler:
   - gcc
#   - clang Clang / libstdc++ bug: https://llvm.org/bugs/show_bug.cgi?id=25861

addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         #- llvm-toolchain-trusty-3.7 # travis-ci/apt-source-whitelist#199

      packages:
         - g++-5
         - gcc-5
         #- clang-3.7
         - libx11-dev
         - libx11-xcb-dev
         - libxcb1-dev
         - libxcb-xkb-dev
         - libxcb-randr0-dev
         - libxcb-keysyms1-dev
         - libxrandr-dev
         - graphviz # VulkanSDK
         - graphviz-dev

before_install:
#   - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee -a /etc/apt/sources.list
#   - wget -O - "http://llvm.org/apt/llvm-snapshot.gpg.key"|sudo apt-key add -
#   - sudo apt-get update -q
#   - sudo apt-get install libvulkan-dev vulkan-utils -y #clang-3.7 -qq
   - git clone https://github.com/EEnginE/travisVulkanBinaries
   - cd travisVulkanBinaries

   - tar -xf cmake.tar.gz
   - CMAKE_EXEC="$(pwd)/cmake-3.5.1-Linux-x86_64/bin/cmake"

   - sudo bash ./vulkansdk-linux-x86_64-1.0.5.0.run
   - cd ..

install:
   - if [[ "$CXX" == "clang++" ]]; then export CXX=clang++-3.7; export CC=clang-3.7; fi
   - if [[ "$CXX" == "g++"     ]]; then export CXX=g++-5;       export CC=gcc-5;     fi

script:
   - mkdir build
   - cd build
   - $CMAKE_EXEC ..
   - if [[ "$CXX" == "clang++-3.7" ]]; then travis_wait make -j2; fi # Building GLEW with clang takes more than 10min https://llvm.org/bugs/show_bug.cgi?id=23708
   - if [[ "$CXX" == "g++-5"       ]]; then             make -j2; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a1f79a324c696ec10d8a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
