#!/bin/bash

generateDefinesHPP() {
   cat << 'EOF'
/*!
 * \file defines.hpp
 * \note This file is automatically generated.
 * Please edit only defines.in.hpp in the project root
 */

#ifndef DEFINES_HPP
#define DEFINES_HPP

EOF

   cat "${INCLUDES_DIR}/${DEBUG_DEF_FILE}"

   echo ""
   echo "// Include export files"
   for I in "${LIBS[@]}"; do
      echo "#include \"${I,,}${EXPORT_FILE_EXT}\""
   done
   echo ""

   cat "defines.in.hpp"

   cat << 'EOF'

#endif // DEFINES_HPP

EOF
}
